config: enable 9P_FSCACHE
clearcontainers/linux pull request #3
Opened 2017-08-28 20:22 UTC by egernst

We need this config update in order to enable 9P mounts to be r/w. Today they are read only, which results in many failed containe workloads.

2017-08-28 20:42 UTC, jcvenegas commented
@egernst so this PR + https://github.com/clearcontainers/agent/pull/93 = fix issues like https://github.com/01org/cc-oci-runtime/issues/669 ?

2017-08-28 20:56 UTC, sboeuf commented
LGTM

2017-08-28 21:03 UTC, mcastelino commented
@egernst is there a dependency between this and https://github.com/clearcontainers/agent/pull/93
Can the new agent work with an older kernel? If so we need to somehow mark that agent-kernel dependency.

2017-08-28 21:28 UTC, egernst commented
@mcastelino - I'll test that and clarify.

2017-08-28 23:42 UTC, miguelinux commented
@egernst @sboeuf @mcastelino @jcvenegas 

I just open an Issue and a PR from this in the packaging project.

https://github.com/clearcontainers/packaging/issues/76
https://github.com/clearcontainers/packaging/pull/77

Could you follow this Issue and PR there pelase.

2017-08-29 10:47 UTC, grahamwhaley requested changes
Until we have resolved https://github.com/clearcontainers/agent/pull/93 I'm going to mark this as 'request changes' to make it clear we may not want to merge yet...

2017-08-29 14:20 UTC, egernst commented
From my measurements, I think we should look @ using mmap instead of fscache as the caching option on 9P.  Based on this, no kernel updates are required (good news!).  Closing this PR.

2017-08-29 14:20 UTC, closed without merging